#!/bin/bash
set -e

cd /etc/pki/ca-trust/extracted/java

src=$1

# Oracle client libs (keep this from old script)
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/oracle/orahome"

# Environment used by python code
export env=dev

# venv
source /home/eqcdrpt/venv_consumption/bin/activate

# Fetch secret + export SECRET_NICK_NAME in SAME shell
source "${HOME}/citidigital/cd_user_consumption/bin/fetch_secret.sh"

# Run the job
python3 "${HOME}/citidigital/cd_user_consumption/bin/gen_user_consumption.py" \
  --env dev \
  --api_source "$src"