SELECT MAX(LENGTH(USER_ID)) AS USER_ID_LEN,
       MAX(LENGTH(USAGE_METHOD)) AS USAGE_METHOD_LEN,
       MAX(LENGTH(SCHEMA_NAME)) AS SCHEMA_NAME_LEN,
       MAX(LENGTH(TABLE_PHYSICAL_NAME)) AS TABLE_PHYSICAL_NAME_LEN,
       MAX(LENGTH(FIELD_LOGICAL_NAME)) AS FIELD_LOGICAL_NAME_LEN,
       MAX(LENGTH(USAGE_TYPE)) AS USAGE_TYPE_LEN,
       MAX(LENGTH(DWH_CREATED_BY)) AS DWH_CREATED_BY_LEN,
       MAX(LENGTH(DWH_UPDATED_BY)) AS DWH_UPDATED_BY_LEN,
       MAX(LENGTH(DWH_UPDATED_REASON)) AS DWH_UPDATED_REASON_LEN,
       MAX(LENGTH(DATA_SOURCE)) AS DATA_SOURCE_LEN
FROM C167969RPC.OM_CATALOGUE_USER_CONSUMPTION;